### ISSUE TITLE
Feature Idea: Better handling of timezones for VSHN Canada

### ISSUE THREAD

**Issue by ccremer** [vshn/odootools#120]
Currently Odootools uses hardcoded timezone "Europe/Zurich".
People that stay in Canada can't really use this tool, as the sign-in and -out times are broken (the calculator spits out very strange numbers for overtime)

Ideas:
- Use timezone from browser (unreliable)
- Add a toggle to use Canada time in the reporting view
- Something else?

**Comment by mhutter** [comment]
Not sure if this can be fixed within odootools only... I remember the situation in Odoo itself being very broken :S

**Comment by ccremer** [comment]
this tool makes its own attendance and shift calculations. All the times saved in Odoo are in UTC. I'm pretty sure we _can_ do something, I'm just not sure yet what exactly is the best solution.
